### ISSUE TITLE
Inverted error guard in C IGRF igrf_set_date_time

### ISSUE THREAD

**Issue by jacobtkeio** [risherlock/adcs#1]
https://github.com/risherlock/ADCS/blob/ba106a611ba78e21fa51388c48dbd9c865aec3bc/codes/onboard_models/igrf/c/igrf.h#L265

This if statement returns 0 (error) only if all error conditions are met, but it should return 0 if one or more error conditions are met.

p.s. Would you be OK with us using your IGRF implementation in a student satellite? See https://github.com/Space-and-Satellite-Systems-UC-Davis/ADCS-Software. We are happy to remove it, just say the word!

**Comment by risherlock** [comment]
Dear @jacobtkeio,

Thanks for the catch and it's fix. I am happy with your team using the software. You might be interested to know that coefficients for IGRF14 has been released. I will be updating the software for IGRF14 very soon. 

Best wishes!

**Comment by risherlock** [comment]
Dear @jacobtkeio,

I am happy to inform you that I have added IGRF-14 and fixed a couple of issues, which you can view here: 80a3e66. You will be glad to know that we now have an interface to choose coordinates using igrf_frame_t. Furthermore, I have tried to validate the implementation against the following sources:

1. https://github.com/wb-bgs/m_IGRF
2. https://github.com/IAGA-VMOD/ppigrf

The results are in close agreement with both implementations.
